# Generated by Django 5.1.6 on 2025-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_votingstatus_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voting_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voting Status (Toggle)',
                'verbose_name_plural': 'Voting Status (Toggle)',
            },
        ),
    ]
