# Generated by Django 5.1.6 on 2025-04-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_votingcontrol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotingControl',
        ),
        migrations.AlterModelOptions(
            name='votingstatus',
            options={'verbose_name': 'Voting Status (Toggle)', 'verbose_name_plural': 'Voting Status (Toggle)'},
        ),
    ]
